[package]
name = "udp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
socket2 = "0.5"
libc = "0.2"
tokio = { version = "1.32.0", features = ["full"] }